### ISSUE TITLE
Assets not found

### ISSUE THREAD

**Issue by fvisticot** [SukumarRaja/flutter_country_code_picker#1]
On iOS I get this error (asset not found), and the flags are not displayed

Unable to load asset: "assets/flags/fr.png".

Exception: Asset not found
When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:295:7)
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
#2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
#9      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:39)
#10     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:470:9)
#11     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:355:5)
#12     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1119:16)
#13     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1069:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5119:11)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#17     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#18     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (81 frames)
#99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#100    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#101    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (33 frames)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#135    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#136    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#138    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#139    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (12 frames)
#151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#152    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#153    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (88 frames)
#241    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#242    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#243    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (9 frames)
#252    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#253    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#254    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (70 frames)
#324    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (25 frames)
#349    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#350    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#351    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (136 frames)
#487    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#488    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#489    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (172 frames)
#661    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#662    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#663    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#664    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#665    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#666    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#667    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#668    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#669    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#670    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#671    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#672    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#673    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#674    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#675    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#676    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#677    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#678    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#679    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#680    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#681    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#682    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#683    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#684    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#685    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#686    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#687    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#688    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#689    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#690    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#691    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#692    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#693    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#694    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#695    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#696    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#697    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#698    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#699    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#700    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#701    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#702    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#703    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#704    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#705    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#706    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#707    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#708    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#709    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#710    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#711    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#712    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#713    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#714    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#715    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#716    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#717    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#718    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#719    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
(elided 3 frames from dart:async)
Image provider: AssetImage(bundle: null, name: "assets/flags/fr.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#ee78d(), name: "assets/flags/fr.png", scale: 1.0)

**Comment by dharanidharandharmasivam** [comment]
Facing the same asset not found issue on running in Android device and kindly find the details below,

![image](https://github.com/SukumarRaja/flutter_country_code_picker/assets/19346074/b223d632-7168-4f0a-af6b-c5feda5acaae)

**Comment by Saqib198** [comment]
I am facing the same issue and still not solved it...
if any know please tell me here....

**Comment by SukumarRaja** [comment]
Bug fixed

**Comment by SukumarRaja** [comment]
Asset issue fixed
